---
title: "Maximum tree height in the Amazon"
output:
  html_document:
    df_print: paged
---

```{r, message=FALSE}
require(ggplot2)
require(raster)
require(tidyverse)
require(tmap)
require(sf)
require(leaflet)
require(sp)
require(gridExtra)
require(magrittr)
require(factoextra) 
require(randomForest)
require(caret)
```

** Run first Exploring variables to create essential variables.**

## Random Forest

```{r}
# separa as variáveis explicativas
input = maximas@data %>% na.omit() %>% select(-altura_cop)
# separa a variável altura maxima
output = maximas@data %>% na.omit() %>% select(altura_cop)
# renomeia a variável
names(output) = c("height")
# normaliza as variáveis explicativas
#inputScaled = input %>% preProcess(method = c("center", "scale")) %>% predict(input)
# salvar parâmetros da normalização
#normParam = preProcess(input, method = c("center", "scale"))
```


```{r}
# cria base com variável dependente original com independente normalizada
#driversScaled = cbind(output, inputScaled)
drivers = cbind(output, input)
# limpa variáveis que não serão mais utilizadas
rm(output, input)
# divide os trasectos em k-folds
#folds = driversScaled %>% row.names() %>% groupKFold(k = 15)           
folds = drivers %>% row.names() %>% groupKFold(k = 15)           

# parametriza os parametros de controle da função train do pacote caret
group_fit_control = trainControl(index = folds, method = "cv")     
# define variáveis dependentes e independentes
res.rf = train(height ~ .,                                         
               #data = driversScaled, # define base de dados
               data = drivers,
               method='rf',          # define modelo a ser treinado
               importance=T,         # análise de importancia para as variaveis
               trControl = group_fit_control) # parâmetros para validação cruzada
print(res.rf)
save(res.rf, file = 'C:/Users/gorge/Documents/GIS DataBase/amazon maximum height extras/objects/randomForest.Rdata')

# limpa da memória parâmetros para Random Forest
rm(folds, group_fit_control)
```

```{r}
# apresenta importância das variáveis com base nos modelos Random Forest
a = varImp(res.rf)
```

```{r}
# normaliza camada uspeed
#uspeedScaled = (uspeed - normParam$mean['uspeed']) / normParam$std['uspeed']
# remove raster original uspeed
#rm(uspeed)

# normaliza camada vspeed
#vspeedScaled = (vspeed - normParam$mean['vspeed']) / normParam$std['vspeed']
# remove raster original uspeed
#rm(vspeed)

# normaliza camada uspeed
#srtmScaled = (srtm - normParam$mean['srtm']) / normParam$std['srtm']
# remove raster original uspeed
#rm(srtm)

#scaledLayers = stack(srtmScaled, uspeedScaled, vspeedScaled)
#names(scaledLayers) = c("srtm", "uspeed", "vspeed")
#rm(srtmScaled, uspeedScaled, vspeedScaled)

```

```{r}

#heightRaster = predict(scaledLayers, res.rf)
heightRaster = predict(layers2estimate, res.rf)
heightRaster = setMinMax(heightRaster)
#writeRaster(heightRaster, filename = 'C:/Users/gorge/Documents/GIS DataBase/amazon maximum height extras/rfHeightRaster.tif')

map = tm_shape(heightRaster) + 
  tm_raster(n = 15,
            palette = "Greens",
            legend.hist = TRUE,
            title = "Maximum height (m)") +
  tm_shape(amaz) + tm_borders() +
  tm_legend(outside = TRUE, hist.width = 2)
#print(map)
tmap_save(map, "./plot/heightRaster_RandomForest.png", width = 1920, height = 1080)

```

