---
title: "Maximum tree height in the Amazon"
output: html_notebook
---

```{r, message=FALSE}
require(ggplot2)
require(raster)
require(tidyverse)
require(tmap)
require(sf)
require(leaflet)
require(sp)
require(gridExtra)
require(magrittr)
require(factoextra) 
require(randomForest)
require(caret)
require(maptools)
require(dismo)
library(rgdal)
library(maps)
library(mapdata)
library(dismo)  
#library(rJava)  
library(jsonlite)

Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jre1.8.0_241')
```

### Envelop by MaxEnt

```{r}
modelEnv<-layers

# Alturas com limites estabelecidos (>50m, >60m, >70m e >75m)
maximas_50<-maximas[maximas$altura_cop>50,]
maximas_60<-maximas[maximas$altura_cop>60,]
maximas_70<-maximas[maximas$altura_cop>70,]
maximas_75<-maximas[maximas$altura_cop>75,]
View(maximas)
```

```{r}

# Coordenadas para a extensão de corte do mapa
model.extent<-extent(min(maximas_50$coords.x1)-10,max(maximas_50$coords.x1)+10,min(maximas_50$coords.x2)-10,max(maximas_50$coords.x2)+10)


# data frame com latitude e longitude
rattlerocc=data.frame(x1=maximas_50[,2],x2=maximas_50[,3]) #first, just make a data frame of latitudes and longitudes for the model


fold <- kfold(rattlerocc, k=5) # add an index that makes five random groups of observations

oco_teste <- rattlerocc[fold == 1, ] # hold out one fifth as test data
oco_treino <- rattlerocc[fold != 1, ] # the other four fifths are training data


rattler.me <- maxent(modelEnv, oco_treino) #note we just using the training data

plot(rattler.me)
response(rattler.me)


modelo_50m <- predict(rattler.me, modelEnv)

plot(modelo_50m, main="Predicted Suitability")
map('worldHires', fill=FALSE, add=TRUE)
points(maximas_50$coords.x1, maximas_50$coords.x2, pch="+", cex=1)


```

# Tree >60 m
```{r}

# data frame com latitude e longitude
rattlerocc=data.frame(x1=maximas_60[,2],x2=maximas_60[,3]) #first, just make a data frame of latitudes and longitudes for the model


fold <- kfold(rattlerocc, k=5) # add an index that makes five random groups of observations

oco_teste <- rattlerocc[fold == 1, ] # hold out one fifth as test data
oco_treino <- rattlerocc[fold != 1, ] # the other four fifths are training data


rattler.me <- maxent(modelEnv, rattlertrain) #note we just using the training data

plot(rattler.me)
response(rattler.me)


modelo_60m <- predict(rattler.me, modelEnv)

plot(modelo_60m, main="Predicted Suitability")
map('worldHires', fill=FALSE, add=TRUE)
points(maximas_60$coords.x1, maximas_60$coords.x2, pch="+", cex=1)


```

# Tree >70 m
```{r}

# data frame com latitude e longitude
rattlerocc=data.frame(x1=maximas_70[,2],x2=maximas_70[,3]) #first, just make a data frame of latitudes and longitudes for the model


fold <- kfold(rattlerocc, k=5) # add an index that makes five random groups of observations

oco_teste <- rattlerocc[fold == 1, ] # hold out one fifth as test data
oco_treino <- rattlerocc[fold != 1, ] # the other four fifths are training data


rattler.me <- maxent(modelEnv, oco_treino) #note we just using the training data

plot(rattler.me)
response(rattler.me)


modelo_70m <- predict(rattler.me, modelEnv)

plot(modelo_70m, main="Predicted Suitability")
map('worldHires', fill=FALSE, add=TRUE)
points(maximas_70$coords.x1, maximas_70$coords.x2, pch="+", cex=1)


```

# Tree >75 m
```{r}

# data frame com latitude e longitude
rattlerocc=data.frame(x1=maximas_75[,2],x2=maximas_75[,3]) #first, just make a data frame of latitudes and longitudes for the model


fold <- kfold(rattlerocc, k=5) # add an index that makes five random groups of observations

oco_teste <- rattlerocc[fold == 1, ] # hold out one fifth as test data
oco_treino <- rattlerocc[fold != 1, ] # the other four fifths are training data


rattler.me <- maxent(modelEnv, oco_treino) #note we just using the training data

plot(rattler.me)
response(rattler.me)


modelo_75m <- predict(rattler.me, modelEnv)

plot(modelo_75m, main="Predicted Suitability")
map('worldHires', fill=FALSE, add=TRUE)
points(maximas_75$coords.x1, maximas_75$coords.x2, pch="+", cex=1)


```

```{r}
par(mfrow=c(1,4))
plot(modelo_50m, main="Predicted Suitability")
map('worldHires', fill=FALSE, add=TRUE)
points(maximas_50$coords.x1, maximas_50$coords.x2, pch="+", cex=1)

plot(modelo_60m, main="Predicted Suitability")
map('worldHires', fill=FALSE, add=TRUE)
points(maximas_60$coords.x1, maximas_60$coords.x2, pch="+", cex=1)

plot(modelo_70m, main="Predicted Suitability")
map('worldHires', fill=FALSE, add=TRUE)
points(maximas_70$coords.x1, maximas_70$coords.x2, pch="+", cex=1)

m<-plot(modelo_75m, main="Predicted Suitability")
map('worldHires', fill=FALSE, add=TRUE)
points(maximas_75$coords.x1, maximas_75$coords.x2, pch="+", cex=1)
m
```

